### ISSUE TITLE
Try to find safe heuristics to split author names into first and family names

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/cff-maven-plugin#3]
This is generally hard, or impossible, but a simple heuristic to prepare the manual curation of names could help.

**Comment by thomaskrause** [comment]
Whatever heuristic I can come up with, would be some kind of regular expression. If you are manually curating the entries, using a text editor with regular expressions support might be better solution. 

I really disagree with the CFF specification about the whole family and first name concept, since there is a lot of cultural implications of splitting names with that in comparison to having a single field. I know that CFF comes from the academic citation background where family names are used as index, but there are valid reasons e.g. for Maven not to split them.

**Comment by sdruskat** [comment]
> I really disagree with the CFF specification about the whole family and first name concept, since there is a lot of cultural implications of splitting names with that in comparison to having a single field. I know that CFF comes from the academic citation background where family names are used as index, but there are valid reasons e.g. for Maven not to split them.

CFF has factored cultural implications into naming those fields (cf. [CFF docs here](https://github.com/citation-file-format/citation-file-format/blob/master/README.md#exemplary-uses-2)), and tries to find a balance between the drawbacks of splitting names and not splitting them for its own purposes.

I do agree, however, that heuristics won't help for our use case, hence closing this.
